xbox:
  profile_url: "https://www.trueachievements.com/gamer/Newerest-5543"
  display_name: "Newerest5543"

psn:
  profile_url: "https://psnprofiles.com/Newerest1"
  display_name: "Newerest1"

retroachievements:
  profile_url: "https://retroachievements.org/user/newerest"
  display_name: "newerest"
